name: Build and deploy ASP.Net Core app to local machine - SECapstoneBE (TestDeploy)

on:
  push:
    branches:
      - testdeploy  # Nhánh để chạy CI/CD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Se_Capstone_Backend/Se_Capstone_Backend.sln

      - name: Build the project
        run: dotnet build ./Se_Capstone_Backend/Capstone.Api/Capstone.Api.csproj --configuration Release

      - name: Publish the project
        run: dotnet publish ./Se_Capstone_Backend/Capstone.Api/Capstone.Api.csproj -c Release -o ${{ github.workspace }}/myapp

      - name: Display publish output
        run: ls -R ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app  # Đặt tên artifact
          path: ${{ github.workspace }}/myapp  # Đường dẫn đến thư mục chứa artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

      - name: Copy files to web server directory
        run: |
          # Kiểm tra xem thư mục có tồn tại không và tạo nó nếu cần
          if [ ! -d /var/www/myapp ]; then
            sudo mkdir -p /var/www/myapp
            sudo chown -R $USER:$USER /var/www/myapp
          fi
          sudo cp -r ${{ github.workspace }}/myapp/* /var/www/myapp/  # Đường dẫn đến thư mục web server của bạn
          sudo systemctl restart your-web-server.service  # Khởi động lại dịch vụ web server (thay thế bằng tên dịch vụ của bạn)

      - name: Run the application
        run: |
          cd /var/www/myapp
          dotnet Capstone.Api.dll &  # Chạy ứng dụng .NET của bạn
